rest_app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_bundle_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api-rest-routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
