rest_app:
    resource: "@RestAppBundle/Controller/"
    type:     annotation
    prefix:   /

app_bundle_api:
    type:     rest
    prefix:   /api
    resource: "@RestAppBundle/Resources/config/api-rest-routing.yml"
