# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # encoders:
    #     FOS\UserBundle\Model\UserInterface: bcrypt
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main:
        #     # activate different ways to authenticate
        #
        #     # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        #     #http_basic: ~
        #
        #     # https://symfony.com/doc/current/security/form_login_setup.html
        #     #form_login: ~
        #     pattern: ^/
        #     form_login:
        #         provider: fos_userbundle
        #         csrf_token_generator: security.csrf.token_manager
        #         # if you are using Symfony < 2.8, use the following config instead:
        #         # csrf_provider: form.csrf_provider
        #
        #     logout:       true
        #     anonymous:    true
        api:
            pattern: ^/                                # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: false                           # Anonymous access is not allowed

    access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
